export const DUMMY_CATEGORIES = [
  { id: "dummy-cat-1", name: "Starters", slug: "starters", display_order: 1, is_active: true, created_at: new Date().toISOString() },
  { id: "dummy-cat-2", name: "Main Course", slug: "main-course", display_order: 2, is_active: true, created_at: new Date().toISOString() },
  { id: "dummy-cat-3", name: "Desserts", slug: "desserts", display_order: 3, is_active: true, created_at: new Date().toISOString() },
  { id: "dummy-cat-4", name: "Beverages", slug: "beverages", display_order: 4, is_active: true, created_at: new Date().toISOString() },
  { id: "dummy-cat-5", name: "Salads", slug: "salads", display_order: 5, is_active: true, created_at: new Date().toISOString() },
  { id: "dummy-cat-6", name: "Breads", slug: "breads", display_order: 6, is_active: true, created_at: new Date().toISOString() },
];

export const DUMMY_MENU_ITEMS = [
  {
    id: "d-1",
    name: "Chicken Tikka",
    description: "Tender chicken pieces marinated in yogurt and spices, grilled to perfection in tandoor",
    price: 180,
    image_url: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=400&q=80",
    dietary_tags: ["spicy"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-1",
    category_name: "Starters",
  },
  {
    id: "d-2",
    name: "Paneer Tikka",
    description: "Cubes of paneer marinated in spiced yogurt and grilled in clay oven",
    price: 160,
    image_url: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&q=80",
    dietary_tags: ["veg"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-1",
    category_name: "Starters",
  },
  {
    id: "d-3",
    name: "Veg Seekh Kebab",
    description: "Spiced vegetable and lentil kebabs, grilled and served with mint chutney",
    price: 120,
    image_url: null,
    dietary_tags: ["veg", "vegan"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-1",
    category_name: "Starters",
  },
  {
    id: "d-4",
    name: "Fish Amritsari",
    description: "Crispy fried fish fillets coated in gram flour batter with Ajwain",
    price: 220,
    image_url: null,
    dietary_tags: ["spicy"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-1",
    category_name: "Starters",
  },
  {
    id: "d-5",
    name: "Hara Bhara Kebab",
    description: "Spinach and green peas patties with aromatic spices",
    price: 130,
    image_url: null,
    dietary_tags: ["veg", "vegan"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-1",
    category_name: "Starters",
  },
  {
    id: "d-6",
    name: "Tandoori Chicken",
    description: "Whole chicken marinated in yogurt and spices, roasted in tandoor",
    price: 250,
    image_url: "https://images.unsplash.com/photo-1610057099443-fde6c99db9e1?w=400&q=80",
    dietary_tags: ["spicy"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-1",
    category_name: "Starters",
  },
  {
    id: "d-7",
    name: "Aloo Tikki",
    description: "Crispy potato patties served with tamarind and green chutney",
    price: 80,
    image_url: null,
    dietary_tags: ["veg", "vegan"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-1",
    category_name: "Starters",
  },
  {
    id: "d-8",
    name: "Paneer Butter Masala",
    description: "Rich and creamy tomato-based curry with soft paneer cubes",
    price: 160,
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400&q=80",
    dietary_tags: ["veg"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-9",
    name: "Butter Chicken",
    description: "Succulent chicken in rich, creamy tomato-butter gravy",
    price: 200,
    image_url: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&q=80",
    dietary_tags: ["spicy"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-10",
    name: "Dal Makhani",
    description: "Slow-cooked black lentils in butter and cream, a classic North Indian delicacy",
    price: 140,
    image_url: "https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=400&q=80",
    dietary_tags: ["veg"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-11",
    name: "Rogan Josh",
    description: "Aromatic lamb curry cooked with Kashmiri spices and yogurt",
    price: 280,
    image_url: null,
    dietary_tags: ["spicy"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-12",
    name: "Malai Kofta",
    description: "Fried paneer and potato dumplings in creamy cashew gravy",
    price: 170,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-13",
    name: "Chicken Biryani",
    description: "Fragrant basmati rice layered with spiced chicken, saffron and fried onions",
    price: 220,
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80",
    dietary_tags: ["spicy"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-14",
    name: "Veg Biryani",
    description: "Aromatic basmati rice with mixed vegetables, saffron and whole spices",
    price: 160,
    image_url: null,
    dietary_tags: ["veg", "vegan"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-15",
    name: "Chole Bhature",
    description: "Spiced chickpea curry served with fluffy deep-fried bread",
    price: 120,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-16",
    name: "Kadai Paneer",
    description: "Paneer cooked in a wok with bell peppers, onions and kadai masala",
    price: 155,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-17",
    name: "Fish Curry",
    description: "Fresh fish in tangy and spicy curry with mustard oil and spices",
    price: 240,
    image_url: null,
    dietary_tags: ["spicy"],
    is_popular: false,
    is_seasonal: true,
    category_id: "dummy-cat-2",
    category_name: "Main Course",
  },
  {
    id: "d-18",
    name: "Gulab Jamun",
    description: "Soft, golden fried milk dumplings soaked in rose-flavored sugar syrup",
    price: 60,
    image_url: "https://images.unsplash.com/photo-1666190077589-09d077939460?w=400&q=80",
    dietary_tags: ["veg"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-3",
    category_name: "Desserts",
  },
  {
    id: "d-19",
    name: "Rasmalai",
    description: "Soft cottage cheese patties immersed in sweet, thickened milk with cardamom",
    price: 70,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-3",
    category_name: "Desserts",
  },
  {
    id: "d-20",
    name: "Rasgulla",
    description: "Spongy cottage cheese balls soaked in light sugar syrup",
    price: 55,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-3",
    category_name: "Desserts",
  },
  {
    id: "d-21",
    name: "Kheer",
    description: "Creamy rice pudding with cardamom, nuts and saffron",
    price: 50,
    image_url: null,
    dietary_tags: ["veg", "gluten-free"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-3",
    category_name: "Desserts",
  },
  {
    id: "d-22",
    name: "Jalebi",
    description: "Crispy, deep-fried spirals soaked in sugar syrup, served warm",
    price: 45,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-3",
    category_name: "Desserts",
  },
  {
    id: "d-23",
    name: "Kulfi Falooda",
    description: "Traditional Indian ice cream with vermicelli, rose syrup and basil seeds",
    price: 80,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: true,
    category_id: "dummy-cat-3",
    category_name: "Desserts",
  },
  {
    id: "d-24",
    name: "Mango Lassi",
    description: "Refreshing yogurt-based drink blended with sweet mango pulp",
    price: 45,
    image_url: "https://images.unsplash.com/photo-1627663059429-4be5a5e189b5?w=400&q=80",
    dietary_tags: ["veg"],
    is_popular: true,
    is_seasonal: true,
    category_id: "dummy-cat-4",
    category_name: "Beverages",
  },
  {
    id: "d-25",
    name: "Fresh Lime Soda",
    description: "Classic lime soda, available sweet or salt",
    price: 35,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-4",
    category_name: "Beverages",
  },
  {
    id: "d-26",
    name: "Masala Chai",
    description: "Traditional Indian tea brewed with aromatic spices and milk",
    price: 25,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-4",
    category_name: "Beverages",
  },
  {
    id: "d-27",
    name: "Lemon Mint Cooler",
    description: "Refreshing blend of lemon, fresh mint, and sparkling water",
    price: 40,
    image_url: null,
    dietary_tags: ["veg", "vegan"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-4",
    category_name: "Beverages",
  },
  {
    id: "d-28",
    name: "Buttermilk (Chaas)",
    description: "Spiced buttermilk with cumin, coriander and a hint of ginger",
    price: 30,
    image_url: null,
    dietary_tags: ["veg", "gluten-free"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-4",
    category_name: "Beverages",
  },
  {
    id: "d-29",
    name: "Fresh Garden Salad",
    description: "Crisp lettuce, cucumbers, tomatoes, and onions with lemon dressing",
    price: 50,
    image_url: null,
    dietary_tags: ["veg", "vegan", "gluten-free"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-5",
    category_name: "Salads",
  },
  {
    id: "d-30",
    name: "Kachumber Salad",
    description: "Diced cucumbers, tomatoes, onions with lemon juice and chaat masala",
    price: 40,
    image_url: null,
    dietary_tags: ["veg", "vegan", "gluten-free"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-5",
    category_name: "Salads",
  },
  {
    id: "d-31",
    name: "Russian Salad",
    description: "Mixed vegetables and fruits in creamy mayonnaise dressing",
    price: 60,
    image_url: null,
    dietary_tags: ["veg", "egg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-5",
    category_name: "Salads",
  },
  {
    id: "d-32",
    name: "Butter Naan",
    description: "Soft leavened bread brushed with butter, baked in tandoor",
    price: 40,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: true,
    is_seasonal: false,
    category_id: "dummy-cat-6",
    category_name: "Breads",
  },
  {
    id: "d-33",
    name: "Garlic Naan",
    description: "Naan topped with fresh garlic and coriander, baked in tandoor",
    price: 50,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-6",
    category_name: "Breads",
  },
  {
    id: "d-34",
    name: "Tandoori Roti",
    description: "Whole wheat bread baked in clay tandoor oven",
    price: 25,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-6",
    category_name: "Breads",
  },
  {
    id: "d-35",
    name: "Laccha Paratha",
    description: "Layered, flaky whole wheat bread with ghee",
    price: 45,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-6",
    category_name: "Breads",
  },
  {
    id: "d-36",
    name: "Stuffed Kulcha",
    description: "Soft leavened bread stuffed with spiced potato and herbs",
    price: 55,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-6",
    category_name: "Breads",
  },
  {
    id: "d-37",
    name: "Tawa Paratha",
    description: "Flaky layered paratha cooked on griddle with ghee",
    price: 35,
    image_url: null,
    dietary_tags: ["veg"],
    is_popular: false,
    is_seasonal: false,
    category_id: "dummy-cat-6",
    category_name: "Breads",
  },
];
